version: "3.8"

services:
  web:
    build: .
    container_name: eums_web
    ports:
      - "8080:80"
    volumes:
      - C:/webserver:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: eums_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eums
      MYSQL_USER: eums
      MYSQL_PASSWORD: eums_13792846
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: eums_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: